### ISSUE TITLE
大佬 数据库面试指南什么时候总结出来呀~

### ISSUE THREAD

**Issue by VirgilG72** [Veal98/cs-wiki#1]
非常感谢大佬辛苦总结出来的计算机基础知识大全~

**Comment by Veal98** [comment]
最近。因为在准备复试，所以每天都在更~

**Comment by VirgilG72** [comment]
> 最近。因为在准备复试，所以每天都在更~

同啊！我也在准备复试 大佬考哪里

**Comment by Veal98** [comment]
> > 最近。因为在准备复试，所以每天都在更~
> 
> 同啊！我也在准备复试 大佬考哪里

东南大学

**Comment by VirgilG72** [comment]
> > > 最近。因为在准备复试，所以每天都在更~
> > 
> > 
> > 同啊！我也在准备复试 大佬考哪里
> 
> 东南大学

强的一批啊 我只是弱弱的暨大  大佬加油！总结的这么用心，一定能过的！
