### ISSUE TITLE
美美与共

### ISSUE THREAD

**Issue by wugenqiang** [Veal98/cs-wiki#2]
你写的真好，昨晚我看了好久

**Comment by Veal98** [comment]
> 你写的真好，昨晚我看了好久

感谢，共同进步 🌺

**Comment by wugenqiang** [comment]
> 老铁，关系数据库笔记里面这个地方并的符号好像出错了

![image](https://user-images.githubusercontent.com/35834667/81802087-06a6cc80-9548-11ea-992c-46cfd679230e.png)

**Comment by Veal98** [comment]
> > 老铁，关系数据库笔记里面这个地方并的符号好像出错了
> 
> ![image](https://user-images.githubusercontent.com/35834667/81802087-06a6cc80-9548-11ea-992c-46cfd679230e.png)

并 union 是这个符号呀 ∪

**Comment by wugenqiang** [comment]
![image](https://user-images.githubusercontent.com/35834667/81807932-8f763600-9551-11ea-99ee-2798085e0239.png)

**Comment by wugenqiang** [comment]
![image-20200513194127798](https://gitee.com/wugenqiang/PictureBed/raw/master/NoteBook/20200513194128.png)

**Comment by wugenqiang** [comment]
括号里面的应该是V符号


 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Veal98"<notifications@github.com&gt;; 
发送时间: 2020年5月13日(星期三) 晚上7:37
收件人: "Veal98/CS-Wiki"<CS-Wiki@noreply.github.com&gt;; 
抄送: "吴跟强"<2422676183@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Veal98/CS-Wiki] 美美与共 (#2)





   
老铁，关系数据库笔记里面这个地方并的符号好像出错了
  

  
并 union 是这个符号呀 ∪

**Comment by Veal98** [comment]
哦哦哦，已修改，感谢指正~ 😊
