### ISSUE TITLE
10-别再恐惧IP协议 有张图写错了

### ISSUE THREAD

**Issue by feverGeek** [Veal98/cs-wiki#6]
![68747470733a2f2f67697465652e636f6d2f7665616c39382f696d616765732f7261772f6d61737465722f696d672f32303231303131353131333831382e706e67](https://user-images.githubusercontent.com/31149082/151650532-de3c2244-7f13-4406-8220-86104bd0c25c.png)
这个与运算的结果底下的十进制写错了吧

**Comment by includevsimport** [comment]
确实，应该是172.20.100.0才对

**Comment by Veal98** [comment]
已改正，多谢大佬~
